name: CI

on: [ workflow_dispatch, push ]

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v1

    - name: Cache PlatformIO
      id: platformio-cache-pip-id
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO Packages
      id: platformio-cache-id
      uses: actions/cache@v1
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-platformio-packages-${{ hashFiles('**/platformio.ini') }}

    - name: Install PlatformIO
      if: steps.platformio-cache-pip-id.outputs.cache-hit != 'true' ||
        steps.platformio-cache-id.outputs.cache-hit != 'true'
      run: |
        wget https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py -O get-platformio.py
        python3 get-platformio.py
        $HOME/.platformio/penv/bin/platformio --version
        
    # Workaround because PlatformIO fails to install the necessary dfu-util package
    # See https://community.platformio.org/t/dfu-suffix-not-found-for-longan-nano-build/16710/4?u=smuehlst
    - name: Install dfu-util
      run: |
        wget -O dfu-util.tgz https://bintray.com/platformio/tool-packages/download_file?file_path=2e415f3-tool-dfuutil-linux_x86_64-1.9.200310.tar.gz
        mkdir -p $HOME/.platformio/packages/tool-dfuutil
        tar -C $HOME/.platformio/packages/tool-dfuutil -x -f dfu-util.tgz

    - name: Build Stepper
      run: |
        $HOME/.platformio/penv/bin/platformio run -d stepper -v
        
    - name: Build MAX6675
      run: |
        $HOME/.platformio/penv/bin/platformio run -d max6675 -v
