name: CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v1

    - name: Cache PlatformIO
      id: platformio-cache-pip-id
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO Binary
      id: platformio-bin-cache-id
      uses: actions/cache@v1
      with:
        path: ~/.local
        key: ${{ runner.os }}-platformio-bin

    - name: Cache PlatformIO Packages
      id: platformio-packages-cache-id
      uses: actions/cache@v1
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-platformio-packages-${{ hashFiles('**/platformio.ini') }}

    - name: Install PlatformIO
      if: steps.platformio-cache-pip-id.outputs.cache-hit != 'true' ||
        steps.platformio-bin-cache-id.outputs.cache-hit != 'true' ||
        steps.platformio-packages-cache-id.outputs.cache-hit != 'true'
      run: |
        pip install -r requirements.txt
        $HOME/.local/bin/platformio --version
        
    - name: Install dfu-util
      run: |
        sudo apt-get --assume-yes install dfu-util
        dfu-util --version
        type dfu-suffix
        mkdir bin
        ln -s /usr/bin/dfu-suffix bin/dfu-suffix

    - name: Build Stepper
      run: |
        type dfu-suffix
        $HOME/.local/bin/platformio run -d stepper -v
        pwd
        
    - name: Build MAX6675
      run: |
        $HOME/.local/bin/platformio run -d max6675 -v
